// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    original_url, short_name, short_url
) VALUES (
    $1, $2, $3
)
RETURNING id, original_url, short_name, short_url, created_at, updated_at
`

type CreateLinkParams struct {
	OriginalUrl sql.NullString
	ShortName   sql.NullString
	ShortUrl    sql.NullString
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.OriginalUrl, arg.ShortName, arg.ShortUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, short_url, created_at, updated_at FROM links
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT id, original_url, short_name, short_url, created_at, updated_at FROM links
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetLinksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetLinks(ctx context.Context, arg GetLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksCount = `-- name: GetLinksCount :one
SELECT COUNT(1) FROM links
`

func (q *Queries) GetLinksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLinksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
    SET original_url = $2,
        short_name = $3
WHERE id = $1
RETURNING id, original_url, short_name, short_url, created_at, updated_at
`

type UpdateLinkParams struct {
	ID          int64
	OriginalUrl sql.NullString
	ShortName   sql.NullString
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
