// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_visits.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT COUNT(1) FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, link_id, ip, user_agent, referer, status, created_at
`

type CreateLinkVisitParams struct {
	LinkID    int64
	Ip        string
	UserAgent sql.NullString
	Referer   sql.NullString
	Status    int32
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRowContext(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAllLinkVisits = `-- name: GetAllLinkVisits :many
SELECT id, link_id, ip, user_agent, referer, status, created_at
FROM link_visits
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllLinkVisitsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllLinkVisits(ctx context.Context, arg GetAllLinkVisitsParams) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinkVisits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkVisitByID = `-- name: GetLinkVisitByID :one
SELECT id, link_id, ip, user_agent, referer, status, created_at
FROM link_visits
WHERE id = $1
`

func (q *Queries) GetLinkVisitByID(ctx context.Context, id int64) (LinkVisit, error) {
	row := q.db.QueryRowContext(ctx, getLinkVisitByID, id)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getVisitsByLinkID = `-- name: GetVisitsByLinkID :many
SELECT id, link_id, ip, user_agent, referer, status, created_at
FROM link_visits
WHERE link_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetVisitsByLinkID(ctx context.Context, linkID int64) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, getVisitsByLinkID, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
