// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
)

type Link struct {
	ID          int64
	OriginalUrl sql.NullString
	ShortName   sql.NullString
	ShortUrl    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
